/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FacilitiesIndexRouteImport } from './routes/facilities/index'
import { Route as FacilitiesIdRouteImport } from './routes/facilities/$id'

const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesIndexRoute = FacilitiesIndexRouteImport.update({
  id: '/facilities/',
  path: '/facilities/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesIdRoute = FacilitiesIdRouteImport.update({
  id: '/facilities/$id',
  path: '/facilities/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/facilities/$id': typeof FacilitiesIdRoute
  '/facilities': typeof FacilitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/facilities/$id': typeof FacilitiesIdRoute
  '/facilities': typeof FacilitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/facilities/$id': typeof FacilitiesIdRoute
  '/facilities/': typeof FacilitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/my-bookings' | '/facilities/$id' | '/facilities'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/my-bookings' | '/facilities/$id' | '/facilities'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/my-bookings'
    | '/facilities/$id'
    | '/facilities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MyBookingsRoute: typeof MyBookingsRoute
  FacilitiesIdRoute: typeof FacilitiesIdRoute
  FacilitiesIndexRoute: typeof FacilitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities/': {
      id: '/facilities/'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities/$id': {
      id: '/facilities/$id'
      path: '/facilities/$id'
      fullPath: '/facilities/$id'
      preLoaderRoute: typeof FacilitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MyBookingsRoute: MyBookingsRoute,
  FacilitiesIdRoute: FacilitiesIdRoute,
  FacilitiesIndexRoute: FacilitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
